# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotFollowerTwFriend',
            fields=[
                ('id_str', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('screen_name', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(default='')),
                ('statuses_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('friends_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.CharField(max_length=50)),
                ('location', models.CharField(default='', max_length=100)),
                ('avg_tweetsperday', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tff_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('need_unfollow', models.BooleanField(default=True)),
            ],
        ),
    ]
